# Generated by Django 5.2.3 on 2025-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Imagen del blog', upload_to='myapp/blog_images/'),
        ),
    ]
