# Generated by Django 5.2.4 on 2025-07-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default='Sin Apellido', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
